PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

-- Table: profil
DROP TABLE IF EXISTS profil;
CREATE TABLE profil (identifiant TEXT NOT NULL UNIQUE PRIMARY KEY,prenom STRING not null,nom STRING not null,email STRING not null,mdp STRING not null,photo NUMERIC, favori TEXT, FOREIGN KEY (favori) REFERENCES Utilisateur (Username)));
CREATE TABLE poll (identifiant_proprietaire STRING not null ,idpoll STRING not null primary key,titre STRING not null,description STRING not null,types STRING(1) not null,status_principal int);
CREATE TABLE liste_questions (idpoll int,idquestion STRING,description_question STRING);
CREATE TABLE notifications (identifiant STRING not null,etat int,message STRING,identifiant_notif STRING,poll_notif int);
CREATE TABLE liste_amis (identifiant STRING not null,identifiant_amis STRING not null,etat int not null);
CREATE TABLE questionnaire_et_aide (idquestion STRING not null,texte STRING not null,reponse int not null);
CREATE TABLE reponse_questionnaire_et_aide (identifiant STRING not null primary key,idquestion STRING not null,reponse_utilisateur STRING);
CREATE TABLE sondage (idpoll STRING not null,data_reponse STRING not null);
CREATE TABLE reponse_sondage (idpoll STRING not null primary key,identifiant STRING not null ,reponse STRING not null,ordre int not null);
CREATE TABLE acces_poll (idpoll STRING not null primary key,identifiant STRING not null,statut_particulier float);
INSERT INTO profil (identifiant,prenom,nom,email,mdp) VALUES("rogerdu","roger","dupont","r.dupont@yopmail.com","ilovesqlite");
INSERT INTO profil (identifiant,prenom,nom,email,mdp) VALUES("c.haron","carl","haroun","c.haroun@yopmail.com", "tuesday");
INSERT INTO profil (identifiant,prenom,nom,email,mdp) VALUES("roger.charles","roger","charles","r.dupont@yopmail.com","titi");
INSERT INTO profil (identifiant,prenom,nom,email,mdp) VALUES("nico","nicolas","dupont","n.dupont@yopmail.com","hello");
INSERT INTO profil (identifiant,prenom,nom,email,mdp) VALUES("arnauddelemelle","arnaud","delemelle","a.delemelle@yopmail.com","good");
INSERT INTO profil (identifiant,prenom,nom,email,mdp) VALUES("antoine.ver","antoine","verlaine","a.verlaine@yopmail.com","ilovesqlite");
INSERT INTO profil (identifiant,prenom,nom,email,mdp) VALUES("donadede","donatien","dede","d.dede@yopmail.com","tomorrow");
INSERT INTO profil (identifiant,prenom,nom,email,mdp) VALUES("louisandrein","louis","andrein","l.andrein@yopmail.com","password");
INSERT INTO profil (identifiant,prenom,nom,email,mdp) VALUES("pierre.jean","pierre","jean","p.jean@yopmail.com","sayit");
INSERT INTO profil (identifiant,prenom,nom,email,mdp) VALUES("camilla.verton","camilla","verton","c.verton@yopmail.com","123456");
INSERT INTO profil (identifiant,prenom,nom,email,mdp) VALUES("florence.jenne","florence","jenne","f.jenne@yopmail.com","mysqlpass");
INSERT INTO profil (identifiant,prenom,nom,email,mdp) VALUES("ingid.pierret","ingrid","pierret","i.pierret@yopmail.com","ilovesqlite");
INSERT INTO profil (identifiant,prenom,nom,email,mdp) VALUES("natasha.civ","Natasha","Civi","n.civi@yopmail.com","kothello");
INSERT INTO poll VALUES("roger.charles",'P1',"Asterosismologie","repondez ci-dessous",'Q',0,0.2);
INSERT INTO poll VALUES("rogerdu",'P2',"Cinema","repondez ci-dessous",'S',NULL,0.5);
INSERT INTO poll VALUES("pierre.jean",'P3',"Dans quelle capitale va t'on ?","repondez ci-dessous",'S',0);
INSERT INTO poll VALUES("nico",'P4',"Quelle est le meilleur language de programmation","repondez ci-dessous",'S',0);
INSERT INTO poll VALUES("ingid.pierret",'P5',"Mathematique","Es-tu un genie ? Pour le savoir repond au question :)",'Q',0.5);
INSERT INTO poll VALUES("ingid.pierret",'P7',"Aide moi a choisir","Quel vêtement dois-je acheter ?",'C',0);
INSERT INTO notifications  VALUES("rogerdu",0,"Pierre Jean a cree un sondage, allez vite y repondre",NULL,'P3');
INSERT INTO notifications  VALUES("c.haron",1,"Donatien Dede vous demande en amis","donadede",NULL);
INSERT INTO notifications  VALUES("arnauddelemelle",1,"Ingrid Pierret demande votre aide",NULL,'P7');
INSERT INTO notifications  VALUES("florence.jenne",1,"Pierre Jean a cree un sondage, allez vite y repondre",NULL,'P3');
INSERT INTO notifications  VALUES("nico",1,"Donatien Dede vous demande en amis","donadede",NULL);
INSERT INTO notifications  VALUES("roger.charles",1,"Pierre Jean a cree un sondage, allez vite y repondre",NULL,'P3');
INSERT INTO notifications  VALUES("arnauddelemelle",0,"Ingrid Pierret a cree un questionnaire, allez vite y repondre",NULL,'P5');
INSERT INTO notifications  VALUES("natasha.civ",0,"Ingrid Pierret a cree un questionnaire, allez vite y repondre",NULL,'P5');
INSERT INTO notifications  VALUES("pierre.jean",0,"Roger Charles a cree un questionnaire, allez vite y repondre",NULL,'P1');
INSERT INTO notifications  VALUES("natasha.civ",0,"Roger Charles a cree un questionnaire, allez vite y repondre",NULL,'P1');
INSERT INTO notifications  VALUES("arnauddelemelle",0,"Roger Charles a cree un questionnaire, allez vite y repondre",NULL,'P1');
INSERT INTO notifications  VALUES("camilla.verton",1,"Roger Dupont a cree un sondage, allez vite y repondre",NULL,'P2');
INSERT INTO notifications  VALUES("donadede",1,"Roger Dupont a cree un sondage, allez vite y repondre",NULL,'P2');
INSERT INTO liste_amis VALUES("donadede","c.haron",0);
INSERT INTO liste_amis VALUES("pierre.jean","rogerdu",1);
INSERT INTO liste_amis VALUES("donadede","nico",0);
INSERT INTO liste_amis VALUES("camilla.verton","c.haron",1);
INSERT INTO liste_amis VALUES("ingid.pierret","arnauddelemelle",1);
INSERT INTO liste_amis VALUES("ingid.pierret","antoine.ver",1);
INSERT INTO liste_amis VALUES("florence.jenne","pierre.jean",1);
INSERT INTO liste_amis VALUES("florence.jenne","natasha.civ",1);
INSERT INTO liste_amis VALUES("arnauddelemelle","nico",1);
INSERT INTO liste_amis VALUES("c.haron","florence.jenne",1);
INSERT INTO liste_amis VALUES("rogerdu","camilla.verton",1);
INSERT INTO liste_amis VALUES("rogerdu","donadede",1);
INSERT INTO liste_amis VALUES("rogerdu","arnauddelemelle",1);
INSERT INTO liste_amis VALUES("antoine.ver","nico",1);
INSERT INTO liste_amis VALUES("nico","louisandrein",1);
INSERT INTO liste_amis VALUES("arnauddelemelle","roger.charles",1);
INSERT INTO liste_questions VALUES('P1',"C1","qu'est-ce que l'asterosismologie?");
INSERT INTO liste_questions VALUES('P1',"C2","Quand est ce que ca a ete cree?");
INSERT INTO liste_questions VALUES('P1',"C3","Est ce toujours d'application?");
INSERT INTO liste_questions VALUES('P5',"C4","Que font 2*2-4?");
INSERT INTO liste_questions VALUES('P5',"C5","Quelle est le plus grand commun diviseur entre 3 et 4?");
INSERT INTO liste_questions VALUES('P7',"C8","Quelle couleur?");
INSERT INTO questionnaire_et_aide VALUES("C1","Une technique d'etude de la structure interne des etoiles.",1);
INSERT INTO questionnaire_et_aide VALUES("C1","Une etude sur les singes",0);
INSERT INTO questionnaire_et_aide VALUES("C1","Une etude sur la vivabilite d'une autre planete",0);
INSERT INTO questionnaire_et_aide VALUES("C2","Dans les annees 90'",0);
INSERT INTO questionnaire_et_aide VALUES("C2","Dans les annees 80'",0);
INSERT INTO questionnaire_et_aide VALUES("C2","En Antiquite",1);
INSERT INTO questionnaire_et_aide VALUES("C3","OUI",1);
INSERT INTO questionnaire_et_aide VALUES("C3","NON",0);
INSERT INTO questionnaire_et_aide VALUES("C4","1",0);
INSERT INTO questionnaire_et_aide VALUES("C4","-1",0);
INSERT INTO questionnaire_et_aide VALUES("C4","Aucune de ces reponses",0);
INSERT INTO questionnaire_et_aide VALUES("C5","1",1);
INSERT INTO questionnaire_et_aide VALUES("C5","2",0);
INSERT INTO questionnaire_et_aide VALUES("C5","3",0);
INSERT INTO questionnaire_et_aide VALUES("C5","4",0);
INSERT INTO questionnaire_et_aide VALUES("C8","Le pantalon rouge",0);
INSERT INTO questionnaire_et_aide VALUES("C8","Le pantalon brun",0);
INSERT INTO reponse_questionnaire_et_aide VALUES("pierre.jean","C1","Une etude sur les singes");
INSERT INTO reponse_questionnaire_et_aide VALUES("pierre.jean","C2","En Antiquite");
INSERT INTO reponse_questionnaire_et_aide VALUES("pierre.jean","C3","NON");
INSERT INTO reponse_questionnaire_et_aide VALUES("natasha.civ","C1","Une etude sur les singes");
INSERT INTO reponse_questionnaire_et_aide VALUES("natasha.civ","C2","Dans les annees 80'");
INSERT INTO reponse_questionnaire_et_aide VALUES("natasha.civ","C3","OUI");
INSERT INTO reponse_questionnaire_et_aide VALUES("arnauddelemelle","C1","Une etude sur les singes");
INSERT INTO reponse_questionnaire_et_aide VALUES("arnauddelemelle","C2","En Antiquite");
INSERT INTO reponse_questionnaire_et_aide VALUES("arnauddelemelle","C4","0");
INSERT INTO reponse_questionnaire_et_aide VALUES("arnauddelemelle","C5","2");
INSERT INTO reponse_questionnaire_et_aide VALUES("antoine.ver","C4","1");
INSERT INTO reponse_questionnaire_et_aide VALUES("antoine.ver","C5","1");
INSERT INTO reponse_questionnaire_et_aide VALUES("arnauddelemelle","C8","Le pantalon brun");
INSERT INTO sondage VALUES('P2',"Forest Gump");
INSERT INTO sondage VALUES('P2',"Minority report");
INSERT INTO sondage VALUES('P2',"Joshua: Teenager vs. Superpower");
INSERT INTO sondage VALUES('P3',"Bruxelle");
INSERT INTO sondage VALUES('P3',"Berlin");
INSERT INTO sondage VALUES('P3',"Washington");
INSERT INTO sondage VALUES('P3',"Rome");
INSERT INTO sondage VALUES('P4',"OZ");
INSERT INTO sondage VALUES('P4',"C++");
INSERT INTO sondage VALUES('P4',"Java");
INSERT INTO sondage VALUES('P4',"C");
INSERT INTO reponse_sondage VALUES('P2',"camilla.verton","Forest Gump",1);
INSERT INTO reponse_sondage VALUES('P2',"camilla.verton","Minority report",3);
INSERT INTO reponse_sondage VALUES('P2',"camilla.verton","Joshua: Teenager vs. Superpower",2);
INSERT INTO reponse_sondage VALUES('P2',"donadede","Forest Gump",2);
INSERT INTO reponse_sondage VALUES('P2',"donadede","Minority report",1);
INSERT INTO reponse_sondage VALUES('P2',"donadede","Joshua: Teenager vs. Superpower",3);
INSERT INTO reponse_sondage VALUES('P3',"florence.jenne","Berlin",4);
INSERT INTO reponse_sondage VALUES('P3',"roger.charles","Rome",4);
INSERT INTO reponse_sondage VALUES('P3',"roger.charles","Bruxelle",3);
INSERT INTO reponse_sondage VALUES('P3',"roger.charles","Washington",2);
INSERT INTO reponse_sondage VALUES('P4',"donadede","OZ",1);
INSERT INTO reponse_sondage VALUES('P4',"donadede","C++",2);
INSERT INTO reponse_sondage VALUES('P4',"donadede","Java",3);
INSERT INTO reponse_sondage VALUES('P4',"donadede","C",4);
INSERT INTO acces_poll VALUES('P1',"pierre.jean",1);
INSERT INTO acces_poll VALUES('P1',"natasha.civ",1);
INSERT INTO acces_poll VALUES('P1',"arnauddelemelle",0.6);
INSERT INTO acces_poll VALUES('P2',"camilla.verton",1);
INSERT INTO acces_poll VALUES('P2',"donadede",1);
INSERT INTO acces_poll VALUES('P3',"rogerdu",0);
INSERT INTO acces_poll VALUES('P3',"florence.jenne",1);
INSERT INTO acces_poll VALUES('P3',"roger.charles",0);
INSERT INTO acces_poll VALUES('P4',"louisandrein",0);
INSERT INTO acces_poll VALUES('P4',"donadede",1);
INSERT INTO acces_poll VALUES('P5',"arnauddelemelle",1);
INSERT INTO acces_poll VALUES('P5',"antoine.ver",1);
INSERT INTO acces_poll VALUES('P5',"arnauddelemelle",0);
INSERT INTO acces_poll VALUES('P5',"antoine.ver",0);
INSERT INTO acces_poll VALUES('P5',"donadede",1);
INSERT INTO acces_poll VALUES('P5',"louisandrein",1);
INSERT INTO acces_poll VALUES('P7',"arnauddelemelle",1);
COMMIT TRANSACTION;
PRAGMA foreign_keys = on;